# Generated by Django 3.1.4 on 2021-01-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_details',
            fields=[
                ('class_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('class_details', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('connect_status', models.IntegerField()),
                ('connect_seek_rating', models.IntegerField()),
                ('connect_teach_rating', models.IntegerField()),
                ('connect_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='connect_status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('connect_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('level', models.CharField(max_length=15)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='language_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'language_list',
            },
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('level', models.CharField(max_length=15)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('rating', models.CharField(max_length=15)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=15)),
                ('last_name', models.CharField(default=None, max_length=15)),
                ('phone', models.DecimalField(decimal_places=0, default=None, max_digits=10)),
                ('address', models.CharField(default=None, max_length=15)),
                ('role', models.IntegerField(default=0)),
                ('seek_designation', models.CharField(default=None, max_length=15)),
                ('teach_designation', models.CharField(default=None, max_length=15)),
                ('seek_skills', models.JSONField()),
                ('teach_skills', models.JSONField()),
                ('country', models.CharField(default='India', max_length=45)),
                ('rate', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('rating', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('image', models.FileField(blank=True, upload_to='profile_images')),
                ('language', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email_id', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=45, null=True)),
                ('skill_description', models.CharField(blank=True, max_length=45, null=True)),
                ('skills', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basic.user_details')),
            ],
            options={
                'db_table': 'skill',
            },
        ),
    ]
