# Generated by Django 3.1.4 on 2021-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_class_details_connect_connect_status_designation_language_list_level_rating_skill_user_details_user_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
