# Generated by Django 3.1.4 on 2020-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_language_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='filter_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=45)),
                ('hourly_rate', models.FloatField()),
                ('talent', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'filter_detils',
            },
        ),
    ]
