# Generated by Django 3.1.4 on 2020-12-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_filter_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basic.user'),
        ),
        migrations.AlterField(
            model_name='filter_details',
            name='hourly_rate',
            field=models.FloatField(default='5'),
        ),
        migrations.AlterField(
            model_name='filter_details',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=45),
        ),
        migrations.AlterField(
            model_name='filter_details',
            name='location',
            field=models.CharField(default='USA', max_length=60),
        ),
        migrations.AlterField(
            model_name='filter_details',
            name='talent',
            field=models.CharField(default='Intermediate', max_length=45),
        ),
    ]
