# Generated by Django 3.1.4 on 2021-01-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20210116_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
