# Generated by Django 3.1.4 on 2021-01-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_delete_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='country',
        ),
    ]
