# Generated by Django 3.1.4 on 2021-01-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
