# Generated by Django 3.1.4 on 2020-12-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20201218_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_details',
            name='hourly_rate',
            field=models.FloatField(blank=True, default='5'),
        ),
        migrations.AlterField(
            model_name='filter_details',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=45),
        ),
        migrations.AlterField(
            model_name='filter_details',
            name='talent',
            field=models.CharField(blank=True, default='Intermediate', max_length=45),
        ),
        migrations.AlterModelTable(
            name='filter_details',
            table='filter_details',
        ),
    ]
