# Generated by Django 3.1.4 on 2021-01-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('sender', models.CharField(max_length=1200)),
                ('receiver', models.CharField(max_length=1200)),
                ('message', models.CharField(max_length=1200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(default='text', max_length=10)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
