# Generated by Django 3.1.4 on 2020-12-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20201218_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
