# Generated by Django 3.1.4 on 2021-01-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comment',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='connect_id',
            field=models.IntegerField(default=0),
        ),
    ]
