# Generated by Django 3.1.4 on 2020-12-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20201229_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
