# Generated by Django 3.1.4 on 2020-12-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20201229_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.user')),
            ],
        ),
    ]
