# Generated by Django 3.1.4 on 2020-12-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
    ]
