# Generated by Django 3.1.4 on 2021-01-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20210130_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='connect_details',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='connect',
            name='connect_title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
