# Generated by Django 3.1.4 on 2021-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_auto_20201229_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='cars'),
        ),
    ]
