# Generated by Django 3.1.4 on 2021-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_auto_20210114_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_details',
            fields=[
                ('class_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('class_details', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
