# Generated by Django 3.1.4 on 2021-01-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_connect_connect_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='filter_details',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.DeleteModel(
            name='Userrole',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.DeleteModel(
            name='filter_details',
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
