# Generated by Django 3.1.4 on 2021-01-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210111_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
